In [ ]:
import pandas as pd

In [ ]:
matches = pd.read_csv("matches.csv", index_col=0)

In [ ]:
matches.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
0,2021-08-14,22:00,La Liga,Matchweek 1,Sat,Away,W,4.0,1.0,Alavés,...,Match Report,NaN,19.0,7.0,18.7,2.0,0.0,0.0,2022,Real Madrid
1,2021-08-22,22:00,La Liga,Matchweek 2,Sun,Away,D,3.0,3.0,Levante,...,Match Report,NaN,20.0,5.0,20.4,1.0,0.0,0.0,2022,Real Madrid
2,2021-08-28,22:00,La Liga,Matchweek 3,Sat,Away,W,1.0,0.0,Betis,...,Match Report,NaN,13.0,3.0,18.3,0.0,0.0,0.0,2022,Real Madrid
3,2021-09-12,21:00,La Liga,Matchweek 4,Sun,Home,W,5.0,2.0,Celta Vigo,...,Match Report,NaN,14.0,10.0,12.8,0.0,1.0,1.0,2022,Real Madrid
5,2021-09-19,21:00,La Liga,Matchweek 5,Sun,Away,W,2.0,1.0,Valencia,...,Match Report,NaN,18.0,10.0,18.4,0.0,0.0,0.0,2022,Real Madrid

In [ ]:
matches.shape

(1558, 27)

In [ ]:
matches["Team"].value_counts()

Real Madrid        114
Eibar               76
Alaves              76
Getafe              76
Levante             76
Valencia            76
Atletico Madrid     76
Osasuna             76
Athletic Club       76
Granada             76
Celta Vigo          76
Villarreal          76
Real Betis          76
Real Sociedad       76
Sevilla             76
Barcelona           76
Valladolid          76
Mallorca            38
Leganes             38
Cadiz               38
Huesca              38
Elche               38
Espanyol            38
Name: Team, dtype: int64

In [ ]:
matches[matches["Team"]=="Real Madrid"]

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
0,2021-08-14,22:00,La Liga,Matchweek 1,Sat,Away,W,4.0,1.0,Alavés,...,Match Report,NaN,19.0,7.0,18.7,2.0,0.0,0.0,2022,Real Madrid
1,2021-08-22,22:00,La Liga,Matchweek 2,Sun,Away,D,3.0,3.0,Levante,...,Match Report,NaN,20.0,5.0,20.4,1.0,0.0,0.0,2022,Real Madrid
2,2021-08-28,22:00,La Liga,Matchweek 3,Sat,Away,W,1.0,0.0,Betis,...,Match Report,NaN,13.0,3.0,18.3,0.0,0.0,0.0,2022,Real Madrid
3,2021-09-12,21:00,La Liga,Matchweek 4,Sun,Home,W,5.0,2.0,Celta Vigo,...,Match Report,NaN,14.0,10.0,12.8,0.0,1.0,1.0,2022,Real Madrid
5,2021-09-19,21:00,La Liga,Matchweek 5,Sun,Away,W,2.0,1.0,Valencia,...,Match Report,NaN,18.0,10.0,18.4,0.0,0.0,0.0,2022,Real Madrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,2020-07-05,14:00,La Liga,Matchweek 34,Sun,Away,W,1.0,0.0,Athletic Club,...,Match Report,NaN,9.0,3.0,15.8,1.0,1.0,1.0,2021,Real Madrid
46,2020-07-10,22:00,La Liga,Matchweek 35,Fri,Home,W,2.0,0.0,Alavés,...,Match Report,NaN,17.0,7.0,19.6,0.0,1.0,1.0,2021,Real Madrid
47,2020-07-13,22:00,La Liga,Matchweek 36,Mon,Away,W,2.0,1.0,Granada,...,Match Report,NaN,11.0,5.0,19.4,0.0,0.0,0.0,2021,Real Madrid
48,2020-07-16,21:00,La Liga,Matchweek 37,Thu,Home,W,2.0,1.0,Villarreal,...,Match Report,NaN,11.0,6.0,19.1,0.0,1.0,1.0,2021,Real Madrid
49,2020-07-19,21:00,La Liga,Matchweek 38,Sun,Away,D,2.0,2.0,Leganés,...,Match Report,NaN,7.0,4.0,15.3,0.0,0.0,0.0,2021,Real Madrid

In [ ]:
matches["Round"].value_counts()

Matchweek 1     41
Matchweek 29    41
Matchweek 22    41
Matchweek 23    41
Matchweek 24    41
Matchweek 25    41
Matchweek 26    41
Matchweek 27    41
Matchweek 28    41
Matchweek 30    41
Matchweek 2     41
Matchweek 31    41
Matchweek 32    41
Matchweek 33    41
Matchweek 34    41
Matchweek 35    41
Matchweek 36    41
Matchweek 37    41
Matchweek 20    41
Matchweek 19    41
Matchweek 21    41
Matchweek 18    41
Matchweek 3     41
Matchweek 4     41
Matchweek 5     41
Matchweek 6     41
Matchweek 7     41
Matchweek 8     41
Matchweek 10    41
Matchweek 11    41
Matchweek 12    41
Matchweek 13    41
Matchweek 14    41
Matchweek 15    41
Matchweek 9     41
Matchweek 16    41
Matchweek 17    41
Matchweek 38    41
Name: Round, dtype: int64

In [ ]:
matches.dtypes

Date             object
Time             object
Comp             object
Round            object
Day              object
Venue            object
Result           object
GF              float64
GA              float64
Opponent         object
xG              float64
xGA             float64
Poss            float64
Attendance      float64
Captain          object
Formation        object
Referee          object
Match Report     object
Notes           float64
Sh              float64
SoT             float64
Dist            float64
FK              float64
PK              float64
PKatt           float64
Season            int64
Team             object
dtype: object

In [ ]:
matches["Date"] = pd.to_datetime(matches["Date"])

In [ ]:
 matches["venue_code"] = matches["Venue"].astype("category").cat.codes

In [ ]:
matches["opponent_code"] = matches["Opponent"].astype("category").cat.codes

In [ ]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Sh,SoT,Dist,FK,PK,PKatt,Season,Team,venue_code,opponent_code
0,2021-08-14,22:00,La Liga,Matchweek 1,Sat,Away,W,4.0,1.0,Alavés,...,19.0,7.0,18.7,2.0,0.0,0.0,2022,Real Madrid,0,0
1,2021-08-22,22:00,La Liga,Matchweek 2,Sun,Away,D,3.0,3.0,Levante,...,20.0,5.0,20.4,1.0,0.0,0.0,2022,Real Madrid,0,14
2,2021-08-28,22:00,La Liga,Matchweek 3,Sat,Away,W,1.0,0.0,Betis,...,13.0,3.0,18.3,0.0,0.0,0.0,2022,Real Madrid,0,4
3,2021-09-12,21:00,La Liga,Matchweek 4,Sun,Home,W,5.0,2.0,Celta Vigo,...,14.0,10.0,12.8,0.0,1.0,1.0,2022,Real Madrid,1,5
5,2021-09-19,21:00,La Liga,Matchweek 5,Sun,Away,W,2.0,1.0,Valencia,...,18.0,10.0,18.4,0.0,0.0,0.0,2022,Real Madrid,0,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2020-07-05,17:00,La Liga,Matchweek 34,Sun,Home,L,0.0,1.0,Leganés,...,7.0,2.0,18.9,1.0,0.0,0.0,2021,Espanyol,1,13
51,2020-07-08,22:00,La Liga,Matchweek 35,Wed,Away,L,0.0,1.0,Barcelona,...,11.0,2.0,18.1,1.0,0.0,0.0,2021,Espanyol,0,3
52,2020-07-12,14:00,La Liga,Matchweek 36,Sun,Home,L,0.0,2.0,Eibar,...,14.0,3.0,20.8,3.0,0.0,0.0,2021,Espanyol,1,7
53,2020-07-16,21:00,La Liga,Matchweek 37,Thu,Away,L,0.0,1.0,Valencia,...,18.0,6.0,21.3,3.0,0.0,0.0,2021,Espanyol,0,21
54,2020-07-19,21:00,La Liga,Matchweek 38,Sun,Home,D,0.0,0.0,Celta Vigo,...,8.0,1.0,17.2,0.0,0.0,0.0,2021,Espanyol,1,5

In [ ]:
 matches["hour"] = matches["Time"].str.replace(":.+", "", regex=True).astype("int")

In [ ]:
matches["day_code"] = matches["Date"].dt.dayofweek

In [ ]:
matches["target"] = (matches["Result"] == "W").astype("int")

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [ ]:
train = matches[matches["Date"] < '2022-01-01']
train

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,venue_code,opponent_code,hour,day_code,target
0,2021-08-14,22:00,La Liga,Matchweek 1,Sat,Away,W,4.0,1.0,Alavés,...,2.0,0.0,0.0,2022,Real Madrid,0,0,22,5,1
1,2021-08-22,22:00,La Liga,Matchweek 2,Sun,Away,D,3.0,3.0,Levante,...,1.0,0.0,0.0,2022,Real Madrid,0,14,22,6,0
2,2021-08-28,22:00,La Liga,Matchweek 3,Sat,Away,W,1.0,0.0,Betis,...,0.0,0.0,0.0,2022,Real Madrid,0,4,22,5,1
3,2021-09-12,21:00,La Liga,Matchweek 4,Sun,Home,W,5.0,2.0,Celta Vigo,...,0.0,1.0,1.0,2022,Real Madrid,1,5,21,6,1
5,2021-09-19,21:00,La Liga,Matchweek 5,Sun,Away,W,2.0,1.0,Valencia,...,0.0,0.0,0.0,2022,Real Madrid,0,21,21,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2020-07-05,17:00,La Liga,Matchweek 34,Sun,Home,L,0.0,1.0,Leganés,...,1.0,0.0,0.0,2021,Espanyol,1,13,17,6,0
51,2020-07-08,22:00,La Liga,Matchweek 35,Wed,Away,L,0.0,1.0,Barcelona,...,1.0,0.0,0.0,2021,Espanyol,0,3,22,2,0
52,2020-07-12,14:00,La Liga,Matchweek 36,Sun,Home,L,0.0,2.0,Eibar,...,3.0,0.0,0.0,2021,Espanyol,1,7,14,6,0
53,2020-07-16,21:00,La Liga,Matchweek 37,Thu,Away,L,0.0,1.0,Valencia,...,3.0,0.0,0.0,2021,Espanyol,0,21,21,3,0
54,2020-07-19,21:00,La Liga,Matchweek 38,Sun,Home,D,0.0,0.0,Celta Vigo,...,0.0,0.0,0.0,2021,Espanyol,1,5,21,6,0

In [ ]:
test = matches[matches["Date"] > '2022-01-01']
test

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,venue_code,opponent_code,hour,day_code,target
25,2022-01-02,14:00,La Liga,Matchweek 19,Sun,Away,L,0.0,1.0,Getafe,...,1.0,0.0,0.0,2022,Real Madrid,0,10,14,6,0
27,2022-01-08,21:00,La Liga,Matchweek 20,Sat,Home,W,4.0,1.0,Valencia,...,1.0,1.0,1.0,2022,Real Madrid,1,21,21,5,1
31,2022-01-23,16:15,La Liga,Matchweek 22,Sun,Home,D,2.0,2.0,Elche,...,1.0,1.0,2.0,2022,Real Madrid,1,8,16,6,0
33,2022-02-06,21:00,La Liga,Matchweek 23,Sun,Home,W,1.0,0.0,Granada,...,1.0,0.0,0.0,2022,Real Madrid,1,11,21,6,1
34,2022-02-12,16:15,La Liga,Matchweek 24,Sat,Away,D,0.0,0.0,Villarreal,...,0.0,0.0,0.0,2022,Real Madrid,0,23,16,5,0
36,2022-02-19,21:00,La Liga,Matchweek 25,Sat,Home,W,3.0,0.0,Alavés,...,2.0,1.0,1.0,2022,Real Madrid,1,0,21,5,1
37,2022-02-26,18:30,La Liga,Matchweek 26,Sat,Away,W,1.0,0.0,Rayo Vallecano,...,0.0,0.0,0.0,2022,Real Madrid,0,17,18,5,1
38,2022-03-05,21:00,La Liga,Matchweek 27,Sat,Home,W,4.0,1.0,Real Sociedad,...,2.0,1.0,1.0,2022,Real Madrid,1,19,21,5,1
40,2022-03-14,21:00,La Liga,Matchweek 28,Mon,Away,W,3.0,0.0,Mallorca,...,0.0,1.0,1.0,2022,Real Madrid,0,15,21,0,1
41,2022-03-20,21:00,La Liga,Matchweek 29,Sun,Home,L,0.0,4.0,Barcelona,...,0.0,0.0,0.0,2022,Real Madrid,1,3,21,6,0
42,2022-04-02,18:30,La Liga,Matchweek 30,Sat,Away,W,2.0,1.0,Celta Vigo,...,0.0,2.0,3.0,2022,Real Madrid,0,5,18,5,1
44,2022-04-09,21:00,La Liga,Matchweek 31,Sat,Home,W,2.0,0.0,Getafe,...,0.0,0.0,0.0,2022,Real Madrid,1,10,21,5,1
46,2022-04-17,21:00,La Liga,Matchweek 32,Sun,Away,W,3.0,2.0,Sevilla,...,0.0,0.0,0.0,2022,Real Madrid,0,20,21,6,1
47,2022-04-20,21:30,La Liga,Matchweek 33,Wed,Away,W,3.0,1.0,Osasuna,...,0.0,0.0,2.0,2022,Real Madrid,0,16,21,2,1
49,2022-04-30,16:15,La Liga,Matchweek 34,Sat,Home,W,4.0,0.0,Espanyol,...,0.0,0.0,0.0,2022,Real Madrid,1,9,16,5,1
51,2022-05-08,21:00,La Liga,Matchweek 35,Sun,Away,L,0.0,1.0,Atlético Madrid,...,1.0,0.0,0.0,2022,Real Madrid,0,2,21,6,0
52,2022-05-12,21:30,La Liga,Matchweek 36,Thu,Home,W,6.0,0.0,Levante,...,1.0,0.0,0.0,2022,Real Madrid,1,14,21,3,1
53,2022-05-15,19:30,La Liga,Matchweek 37,Sun,Away,D,1.0,1.0,Cádiz,...,1.0,0.0,0.0,2022,Real Madrid,0,6,19,6,0
54,2022-05-20,21:00,La Liga,Matchweek 38,Fri,Home,D,0.0,0.0,Betis,...,0.0,0.0,0.0,2022,Real Madrid,1,4,21,4,0

In [ ]:
predictors = ["venue_code", "opponent_code", "hour", "day_code"]

In [ ]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [ ]:
preds = rf.predict(test[predictors])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(test["target"], preds)
accuracy

0.5789473684210527

In [ ]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds))
combined

    actual  prediction
25       0           0
27       1           1
31       0           1
33       1           1
34       0           0
36       1           1
37       1           0
38       1           1
40       1           0
41       0           0
42       1           0
44       1           1
46       1           0
47       1           0
49       1           1
51       0           0
52       1           0
53       0           1
54       0           0

In [ ]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction  0  1
actual
0           5  2
1           6  6

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
precision_score(test["target"], preds)

0.75

In [ ]:
 grouped_matches = matches.groupby("Team")

In [ ]:
group = grouped_matches.get_group("Barcelona")
group

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,venue_code,opponent_code,hour,day_code,target
0,2020-09-27,21:00,La Liga,Matchweek 3,Sun,Home,W,4.0,0.0,Villarreal,...,1.0,1.0,1.0,2022,Barcelona,1,23,21,6,1
1,2020-10-01,21:30,La Liga,Matchweek 4,Thu,Away,W,3.0,0.0,Celta Vigo,...,1.0,0.0,0.0,2022,Barcelona,0,5,21,3,1
2,2020-10-04,21:00,La Liga,Matchweek 5,Sun,Home,D,1.0,1.0,Sevilla,...,1.0,0.0,0.0,2022,Barcelona,1,20,21,6,0
3,2020-10-17,21:00,La Liga,Matchweek 6,Sat,Away,L,0.0,1.0,Getafe,...,1.0,0.0,0.0,2022,Barcelona,0,10,21,5,0
5,2020-10-24,16:00,La Liga,Matchweek 7,Sat,Home,L,1.0,3.0,Real Madrid,...,1.0,0.0,0.0,2022,Barcelona,1,18,16,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,2020-07-05,22:00,La Liga,Matchweek 34,Sun,Away,W,4.0,1.0,Villarreal,...,2.0,0.0,0.0,2021,Barcelona,0,23,22,6,1
45,2020-07-08,22:00,La Liga,Matchweek 35,Wed,Home,W,1.0,0.0,Espanyol,...,2.0,0.0,0.0,2021,Barcelona,1,9,22,2,1
46,2020-07-11,19:30,La Liga,Matchweek 36,Sat,Away,W,1.0,0.0,Valladolid,...,1.0,0.0,0.0,2021,Barcelona,0,22,19,5,1
47,2020-07-16,21:00,La Liga,Matchweek 37,Thu,Home,L,1.0,2.0,Osasuna,...,5.0,0.0,0.0,2021,Barcelona,1,16,21,3,0
48,2020-07-19,17:00,La Liga,Matchweek 38,Sun,Away,W,5.0,0.0,Alavés,...,1.0,0.0,0.0,2021,Barcelona,0,0,17,6,1

In [ ]:
def rolling_averages(group, columns, new_columns):
  group = group.sort_values("Date")
  rolling_stats = group[columns].rolling(3, closed='left').mean()
  group[new_columns] = rolling_stats
  group = group.dropna(subset=new_columns)
  return group

In [ ]:
columns = ["GF", "GA", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]
new_columns = [f"{c}_rolling" for c in columns]
new_columns

['GF_rolling',
 'GA_rolling',
 'Sh_rolling',
 'SoT_rolling',
 'Dist_rolling',
 'FK_rolling',
 'PK_rolling',
 'PKatt_rolling']

In [ ]:
rolling_averages(group, columns, new_columns)

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,day_code,target,GF_rolling,GA_rolling,Sh_rolling,SoT_rolling,Dist_rolling,FK_rolling,PK_rolling,PKatt_rolling
3,2019-09-14,21:00,La Liga,Matchweek 4,Sat,Home,W,5.0,2.0,Valencia,...,5,1,2.333333,1.666667,13.000000,4.333333,16.500000,0.000000,0.000000,0.000000
5,2019-09-21,21:00,La Liga,Matchweek 5,Sat,Away,L,0.0,2.0,Granada,...,5,0,4.000000,2.000000,15.000000,7.000000,18.633333,0.000000,0.000000,0.000000
6,2019-09-24,21:00,La Liga,Matchweek 6,Tue,Home,W,2.0,1.0,Villarreal,...,1,1,2.333333,2.000000,11.000000,5.000000,20.366667,0.666667,0.000000,0.000000
7,2019-09-28,16:00,La Liga,Matchweek 7,Sat,Away,W,2.0,0.0,Getafe,...,5,1,2.333333,1.666667,11.000000,5.000000,19.100000,1.000000,0.000000,0.000000
9,2019-10-06,21:00,La Liga,Matchweek 8,Sun,Home,W,4.0,0.0,Sevilla,...,6,1,1.333333,1.000000,8.666667,3.666667,18.900000,1.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,2021-05-02,21:00,La Liga,Matchweek 34,Sun,Away,W,3.0,2.0,Valencia,...,6,1,2.666667,1.666667,13.000000,4.666667,15.166667,0.666667,0.333333,0.333333
50,2021-05-08,16:15,La Liga,Matchweek 35,Sat,Home,D,0.0,0.0,Atlético Madrid,...,5,0,2.000000,1.666667,14.666667,4.666667,15.033333,1.333333,0.000000,0.333333
51,2021-05-11,22:00,La Liga,Matchweek 36,Tue,Away,D,3.0,3.0,Levante,...,1,0,1.333333,1.333333,13.666667,5.333333,15.900000,1.666667,0.000000,0.333333
52,2021-05-16,18:30,La Liga,Matchweek 37,Sun,Home,L,1.0,2.0,Celta Vigo,...,6,0,2.000000,1.666667,14.000000,5.666667,15.100000,1.666667,0.000000,0.333333
53,2021-05-22,18:00,La Liga,Matchweek 38,Sat,Away,W,1.0,0.0,Eibar,...,5,1,1.333333,1.666667,16.666667,5.333333,15.800000,1.000000,0.000000,0.000000

In [ ]:
matches_rolling = matches.groupby("Team").apply(lambda x:rolling_averages(x, columns, new_columns) )
matches_rolling

                    Date   Time     Comp         Round  Day Venue Result   GF  \
Team
Alaves     3  2019-09-15  14:00  La Liga   Matchweek 4  Sun  Home      L  0.0
           4  2019-09-22  18:30  La Liga   Matchweek 5  Sun  Away      L  0.0
           5  2019-09-26  21:00  La Liga   Matchweek 6  Thu  Away      L  0.0
           6  2019-09-29  16:00  La Liga   Matchweek 7  Sun  Home      W  2.0
           7  2019-10-05  18:30  La Liga   Matchweek 8  Sat  Away      L  1.0
...                  ...    ...      ...           ...  ...   ...    ...  ...
Villarreal 51 2021-05-02  16:15  La Liga  Matchweek 34  Sun  Home      W  1.0
           53 2021-05-09  18:30  La Liga  Matchweek 35  Sun  Home      L  2.0
           54 2021-05-13  19:00  La Liga  Matchweek 36  Thu  Away      W  2.0
           55 2021-05-16  18:30  La Liga  Matchweek 37  Sun  Home      W  4.0
           56 2021-05-22  18:00  La Liga  Matchweek 38  Sat  Away      L  1.0

                GA       Opponent  ...  day_code  target  GF_rolling  \
Team                               ...
Alaves     3   1.0        Sevilla  ...         6       0    0.666667
           4   2.0  Athletic Club  ...         6       0    0.333333
           5   3.0  Real Sociedad  ...         3       0    0.333333
           6   0.0       Mallorca  ...         6       1    0.000000
           7   2.0       Valencia  ...         5       0    0.666667
...            ...            ...  ...       ...     ...         ...
Villarreal 51  0.0         Getafe  ...         6       1    2.333333
           53  4.0     Celta Vigo  ...         6       0    1.000000
           54  0.0     Valladolid  ...         3       1    1.333333
           55  0.0        Sevilla  ...         6       1    1.666667
           56  2.0    Real Madrid  ...         5       0    2.666667

               GA_rolling Sh_rolling SoT_rolling Dist_rolling FK_rolling  \
Team
Alaves     3     0.333333   8.000000    1.666667    15.100000   0.333333
           4     0.666667   7.333333    1.000000    14.733333   0.000000
           5     1.333333   5.333333    0.666667    15.433333   0.000000
           6     2.000000   5.333333    0.333333    16.900000   0.000000
           7     1.666667   6.333333    2.000000    18.700000   0.000000
...                   ...        ...         ...          ...        ...
Villarreal 51    1.666667  11.333333    5.000000    14.900000   0.000000
           53    1.333333   8.000000    3.666667    16.166667   0.000000
           54    2.000000   9.666667    4.333333    16.266667   0.000000
           55    1.333333   9.333333    4.000000    17.466667   0.000000
           56    1.333333  12.000000    4.666667    17.733333   0.333333

               PK_rolling  PKatt_rolling
Team
Alaves     3     0.000000       0.000000
           4     0.000000       0.000000
           5     0.000000       0.000000
           6     0.000000       0.000000
           7     0.333333       0.333333
...                   ...            ...
Villarreal 51    0.000000       0.000000
           53    0.000000       0.000000
           54    0.333333       0.333333
           55    0.333333       0.333333
           56    0.333333       0.333333

[1486 rows x 40 columns]

In [ ]:
matches_rolling.index = range(matches_rolling.shape[0])
matches_rolling

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,day_code,target,GF_rolling,GA_rolling,Sh_rolling,SoT_rolling,Dist_rolling,FK_rolling,PK_rolling,PKatt_rolling
0,2019-09-15,14:00,La Liga,Matchweek 4,Sun,Home,L,0.0,1.0,Sevilla,...,6,0,0.666667,0.333333,8.000000,1.666667,15.100000,0.333333,0.000000,0.000000
1,2019-09-22,18:30,La Liga,Matchweek 5,Sun,Away,L,0.0,2.0,Athletic Club,...,6,0,0.333333,0.666667,7.333333,1.000000,14.733333,0.000000,0.000000,0.000000
2,2019-09-26,21:00,La Liga,Matchweek 6,Thu,Away,L,0.0,3.0,Real Sociedad,...,3,0,0.333333,1.333333,5.333333,0.666667,15.433333,0.000000,0.000000,0.000000
3,2019-09-29,16:00,La Liga,Matchweek 7,Sun,Home,W,2.0,0.0,Mallorca,...,6,1,0.000000,2.000000,5.333333,0.333333,16.900000,0.000000,0.000000,0.000000
4,2019-10-05,18:30,La Liga,Matchweek 8,Sat,Away,L,1.0,2.0,Valencia,...,5,0,0.666667,1.666667,6.333333,2.000000,18.700000,0.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481,2021-05-02,16:15,La Liga,Matchweek 34,Sun,Home,W,1.0,0.0,Getafe,...,6,1,2.333333,1.666667,11.333333,5.000000,14.900000,0.000000,0.000000,0.000000
1482,2021-05-09,18:30,La Liga,Matchweek 35,Sun,Home,L,2.0,4.0,Celta Vigo,...,6,0,1.000000,1.333333,8.000000,3.666667,16.166667,0.000000,0.000000,0.000000
1483,2021-05-13,19:00,La Liga,Matchweek 36,Thu,Away,W,2.0,0.0,Valladolid,...,3,1,1.333333,2.000000,9.666667,4.333333,16.266667,0.000000,0.333333,0.333333
1484,2021-05-16,18:30,La Liga,Matchweek 37,Sun,Home,W,4.0,0.0,Sevilla,...,6,1,1.666667,1.333333,9.333333,4.000000,17.466667,0.000000,0.333333,0.333333
1485,2021-05-22,18:00,La Liga,Matchweek 38,Sat,Away,L,1.0,2.0,Real Madrid,...,5,0,2.666667,1.333333,12.000000,4.666667,17.733333,0.333333,0.333333,0.333333

In [ ]:
def make_predicitons(data, predictors):
  train = data[data["Date"] < '2022-01-01']
  test = data[data["Date"] > '2022-01-01']
  rf.fit(train[predictors], train["target"])
  preds = rf.predict(test[predictors])
  combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))
  precision = precision_score(test["target"], preds)
  return combined,precision

In [ ]:
combined, precision = make_predicitons (matches_rolling, predictors + new_columns)
combined

      actual  predicted
1102       0          1
1103       1          1
1104       0          1
1105       1          1
1106       0          1
1107       1          1
1108       1          1
1109       1          1
1110       1          1
1111       0          1
1112       1          0
1113       1          1
1114       1          0
1115       1          0
1116       1          1
1117       0          0
1118       1          1
1119       0          1
1120       0          1

In [ ]:
precision

0.6

In [ ]:
combined = combined.merge(matches_rolling[["Date","Team","Opponent","Result"]], left_index=True, right_index=True)
combined

      actual  predicted       Date         Team         Opponent Result
1102       0          1 2022-01-02  Real Madrid           Getafe      L
1103       1          1 2022-01-08  Real Madrid         Valencia      W
1104       0          1 2022-01-23  Real Madrid            Elche      D
1105       1          1 2022-02-06  Real Madrid          Granada      W
1106       0          1 2022-02-12  Real Madrid       Villarreal      D
1107       1          1 2022-02-19  Real Madrid           Alavés      W
1108       1          1 2022-02-26  Real Madrid   Rayo Vallecano      W
1109       1          1 2022-03-05  Real Madrid    Real Sociedad      W
1110       1          1 2022-03-14  Real Madrid         Mallorca      W
1111       0          1 2022-03-20  Real Madrid        Barcelona      L
1112       1          0 2022-04-02  Real Madrid       Celta Vigo      W
1113       1          1 2022-04-09  Real Madrid           Getafe      W
1114       1          0 2022-04-17  Real Madrid          Sevilla      W
1115       1          0 2022-04-20  Real Madrid          Osasuna      W
1116       1          1 2022-04-30  Real Madrid         Espanyol      W
1117       0          0 2022-05-08  Real Madrid  Atlético Madrid      L
1118       1          1 2022-05-12  Real Madrid          Levante      W
1119       0          1 2022-05-15  Real Madrid            Cádiz      D
1120       0          1 2022-05-20  Real Madrid            Betis      D